# Generated by Django 4.2 on 2023-04-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(default='Somewhere', on_delete=django.db.models.deletion.CASCADE, related_name='country', to='accounts.countries'),
        ),
    ]
